sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t natnathou/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true natnathou/react-test npm run test

after_success:
  - docker build -t natnathou/multi-client ./client
  - docker build -t natnathou/multi-nginx ./nginx
  - docker build -t natnathou/multi-server ./server
  - docker build -t natnathou/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push natnathou/multi-client
  - docker push natnathou/multi-nginx
  - docker push natnathou/multi-server
  - docker push natnathou/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket-name: 'elasticbeanstalk-us-east-2-819989340981'
  bucket-path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
