sudo: required

language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket-name: 'elasticbeanstalk-us-east-2-819989340981'
  bucket-path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
